### ISSUE TITLE
Running Groovy LS from CLI

### ISSUE THREAD

**Issue by har-pi** [palantir/language-servers#164]
Hallo,

Have gotten a little baffled up trying to create something executable from the command line for Groovy LS.
I want to connect it with my neovim LSP client.

Any instructions to get through this?

**Comment by jiahuijiang** [comment]
Hey! we don't have a written instruction on running the server from command line. But it's very straightforward - groovy-ls is published to bintray as executable jars https://bintray.com/palantir/releases/language-servers/0.4.3, it doesn't take any extra arguments during startup time.
So in order to connect to it, simply doing "java -jar groovy-language-server.jar" and send all the requests in the LSP specified format will work

**Comment by gatesn** [comment]
Closing this out
